#!/bin/bash
#sysintegration assignment 1
# Stephen O'Neill C133317851

#clear screen
clear

#bring user to their specific directory (ensures pw works)
cd /home
cd $whoami

#declare functions
fun_exit()
{
	clear
	echo "GOODBYE"
	exit
}

fun_pwd()
{
	echo "$(pwd)"
}

fun_ip()
{
	echo "$(ifconfig eno1)"
}

fun_date()
{
	echo "$(date +%Y%m%d%H%M%S)"
}

fun_ud()
{
	echo "$(id -u) $(id -g) $(whoami) $(id -gn)"
	DIR=/home
	stat -c '%i' $DIR
}

fun_ls()
{
	echo "$(ls)"
}
#creates file for user
fun_file()
{
	echo "Please enter name of the file"
	read file_name
	if [ -e $file_name ]
	then
		echo "sorry file already exists, enter another name"

	else
		touch $file_name
	fi
}
#edit file for user
fun_edit()
{
	echo "Please enter name of the file you wish to edit"
        read file_name
        nano $file_name
}

fun_del()
{
        echo "enter file name you wish to delete"
        read del_file
        rm $del_file
}


fun_help()
{
	echo "HI $(whoami), i see youre having some trouble"
	echo "These are the commands available to you"
	echo "Simply type one of these and hit enter :D"
	echo " pw : prints working directory"
	echo "ifc : prints ip configuration"
	echo " dt : prints off the current date and time"
        echo " ud : prints userID,groupID,username,groupname,iNODE of users home directory"
	echo "file: create a file in youre directory"
	echo "edit: edit a file specified"
	echo "help: prints this screen :D"
	echo "exit: exits the shell and logs you out"

}

#creates while loop that will continue to run until exit
while :
do
	#display menu
	echo "====================================================="
	echo "=============Hello $(whoami) enter a command============="
	echo "====================================================="
	read option

	case $option in
		"pw")	fun_pwd;;
	       "ifc")   fun_ip;;
	        "dt")   fun_date;;
		"ud")   fun_ud;;
	      "help")   fun_help;;
	      "list")   fun_ls;;
	      "file")	fun_file;;
  	      "edit")   fun_edit;;
	    "delete")	fun_del;;
              "exit")	fun_exit;;
		   *)	echo "command not allowed please enter another or type: help to list all available to you";;
	esac
done





























